=== Assignment: Generate HTML content ===

Clicking on one of the items on the home page leads to a static jpeg image:
https://d123.cloudfront.net/card/960w/da8398f4.jpg

Let's have an html page with details about the card using URI path like this one:
https://d123.cloudfront.net/card/da8398f4

We generate HTML content in Lambda functions associated with viewer-request or
origin-request event triggers. Let's do it with origin-request this time so
that the generated content can be cached by CloudFront distribution!

1. Locate the HTML template

   https://s3.console.aws.amazon.com/s3/buckets/ws-lambda-edge-UNIQUE_ID/?region=us-east-1&tab=overview

   /template/card.html is a simple template for the card page

2. Create a Lambda function

   Name:          ws-lambda-at-edge-generate-card-page
   Role:          Choose an existing role
   Existing role: ws-lambda-at-edge-read-only-<UNIQUE_ID>

   Use the blueprint: ./ws-lambda-at-edge-generate-card-page.js

4. Validate the function works with test-invoke in Lambda Console

   Use event template "CloudFront Simple Remote Call".
   Validate the request object is unchanged, unless it matches the pattern /card/[a-z0-9]+.
   In case it matches the patter, validate the HTML page is returned
   in the generated response.

5. Publish the function and associate it CloudFront distribution

   Associate the function version with origin-request event of the default
   cache behavior. Wait for 30-60 seconds.

6. Validate CloudFront distribution now serves the content generated by Lambda@Edge

   The default root object loaded at:
   https://d123.cloudfront.net

   Should now point to card details pages generated by Lambda@Edge
   https://d123.cloudfront.net/card/da8398f4
